import fileinput
import re
import sys
from xml.sax.saxutils import unescape


for line in fileinput.input("-"):
    new_line = unescape(line, {
        "&times": "×",
        "&#043;": "+",
        "&#061;": "=",
        "&#037;": "%",
        "&rArr": "⇒",
        "&rho;": "ρ",
        "&hellip;": "...",
        "&Lambda;": "Λ",
        "&Delta;": "Δ",
        "&Omega;": "Ω",
        "&Sigma;": "Σ",
        "&Phi;": "Φ",
        "&Gamma;": "Ɣ",
        "&Eacute;": "É",
        "&eacute;": "é",
        "&rarr;": "→",
        "&omega;": "ω",
        "&alpha;": "α",
        "&isin;": "∈",
        "&lambda;": "λ",
        "&phi;": "φ",
        "&pi;": "π",
        "&le;": "≤",
        "&sigma;": "σ",
        "&mu;": "μ",
        "&gamma;": "γ",
        "&fnof;": "ƒ",
        "&epsilon;": "ε",
        "&infin;": "∞",
        "&beta;": "β",
        "&delta;": "δ",
        "&ge;": "≥",
        "&tau;": "τ",
        "&theta;": "θ",
        "&lowast;": "∗",
        "&larr;": "←",
        "&equiv;": "≡",
        "&cap;": "∩",
        "&nu;": "ν",
        "&cup;": "∪",
        "&oplus;": "⊕",
        "&plusmn;": "±",
        "&ne;": "≠",
        "&sube;": "⊆",
        "&not;": "¬",
        "&radic;": "√",
        "&forall;": "∀",
        "&sub;": "⊂",
        "&psi;": "ψ",
        "&chi;": "χ",
        "&otimes;": "⊗",
        "&harr;": "↔",
        "&exist;": "∃",
        "&nabla;": "∇",
        "&eta;": "η",
        "&cong;": "≅",
        "&zeta;": "ζ",
        "&darr;": "↓",
        "&xi;": "ξ",
        "&perp;": "⊥",
        "&alefsym;": "ℵ",
        "&sum;": "∑",
        "&sect;": "§",
        "&uarr;": "↑",
        "&asymp;": "≈",
        "&reg;": "®",
        "&empty;": "∅",
        "&part;": "∂",
        "&ccedil;": "ç",
        "&atilde;": "ã",
        "&ntilde;": "ñ",
        "&notin;": "∉",
        "&agrave;": "à",
        "&sim;": "∼",
        "&oacute;": "ó",
        "&aelig;": "æ",
        "&iacute;": "í",
        "&weierp;": "℘",
        "&trade;": "™",
        "&oelig;": "œ",
        "&iota;": "ι",
        "&szlig;": "ß",
        "&sup;": "⊃",
        "&ecirc;": "ê",
        "&copy;": "©",
        "&aring;": "å",
        "&uacute;": "ú",
        "&sigmaf;": "ς",
        "&iuml;": "ï",
        "&upsilon;": "υ",
        "&ocirc;": "ô",
        "&pound;": "£",
        "&deg;": "°",
        "&aacute;": "á",
        "&oslash;": "ø",
        "&ouml;": "ö",
        "&uuml;": "ü",
        "&auml;": "ä",
        "&egrave;": "è",
        "&quot;": '"',
    })

    new_line = new_line.replace("…", "...")

    sys.stdout.write(new_line)

    if re.search("&(?!nbsp|ndash|mdash|prime|minus)[a-zA-Z#0-9]+;", new_line):
        sys.stderr.write(new_line)
